\context ChordNames
	\chords {
		\set chordChanges = ##t

		% intro
		s2
		c2 d2:m/c e2:m/c d2:m/c
		c2 d2:m/c e2:m/c d2:m/c

		% estrofa 1
		c2 a2:7 d2:m d2:m7
		g2 g2:7 c2 c2
		c2 a2:7 d2:m f2:m
		r2 c2 g2 c4 f4 c2

		% estrofa 2
		c2 a2:7 d2:m d2:m7
		g2 g2:7 c2 c2
		c2 a2:7 d2:m f2:m
		r2 c2 g2 c4 f4 c2

		% estrofa 3
		c2 a2:7 d2:m d2:m7
		g2 g2:7 c2 c2
		c2 a2:7 d2:m f2:m
		r2 c2 g2 g2

		% glue
		c2 d2:m e2:m f2 g2 c2:7

		% parte b
		f2 c2 d2:m d2:m7
		g2:m g2:m7 c2 c2:7
		f2 f2:7 bf2 bf2:m
		f2 c2 c2 f2
		f2 g2:7 r2

		% estrofa 1
		c2 a2:7 d2:m d2:m7
		g2 g2:7 c2 c2
		c2 a2:7 d2:m f2:m
		r2 c2 g2 g2

		% glue
		c2 d2:m e2:m f2 g2 c2:7

		% parte b
		f2 r2*14
		f2 f2 g2:7 r2

		% estrofa 2
		c2 a2:7 d2:m d2:m7
		g2 g2:7 c2 c2
		c2 a2:7 d2:m f2:m
		r2 c2 g2 c4 f4 c2
	}
