\lyricsto "voice 1" \new Lyrics \lyricmode {
	\set stanza = "1. "
	"Na" "vi" "dad," "Na" "vi" "dad," "u" "na_es" "tre" "lla" "bri" "lla" "rá,"
	"Na" "vi" "dad," "Na" "vi" "dad," "al" "na" "cer" "el" "ni" "ño" "Dios,"
	"Na" "vi" "dad," "Na" "vi" "dad," "es" "ta" "fe" "cha" "tan" "fe" "liz,"
	"es" "ta" "re" "mos" "con" "el" "rey."
	"Na" "vi"
} % Lyrics

\lyricsto "voice 1" \new Lyrics \lyricmode {
	\set stanza = "2. "
	"Na" "vi" 
	"dad," "Na" "vi" "dad," "na" "ci" "mien" "to" "de" "Je" "sús,"
	"Na" "vi" "dad," "Na" "vi" "dad," "blan" "ca_es" "te" "la" "de" "quie" "tud,"
	"Na" "vi" "dad," "Na" "vi" "dad," "un" "e" "ter" "no" "res" "plan" "dor,"
	"de" "fe" "li" "ci" "dad" "y_a" "mor."
} % Lyrics

\lyricsto "voice 1" \new Lyrics \lyricmode {
	\set stanza = "3. "
	"Na" "vi" "dad," "Na" "vi" "dad," "u" "na" "voz" "de_e" "ter" "ni" "dad,"
	"Na" "vi" "dad," "Na" "vi" "dad," "u" "na" "voz" "de" "sal" "va" "ción,"
	"Na" "vi" "dad," "Na" "vi" "dad," "la_es" "pe" "ran" "za_en" "la_o" "ra" "ción,"
	"y_el" "mi" "la" "gro" "del" "a" "mor."
} % Lyrics
