\lyricsto "voice 1" \new Lyrics \lyricmode {
	\set stanza = "1. "
	"Na" -- "vi" -- "dad," "Na" -- "vi" -- "dad," "u" -- "na es" -- "tre" -- "lla" "bri" -- "lla" -- "rá,"
	"Na" -- "vi" -- "dad," "Na" -- "vi" -- "dad," "al" "na" -- "cer" "el" "ni" -- "ño" "Dios,"
	"Na" -- "vi" -- "dad," "Na" -- "vi" -- "dad," "es" -- "ta" "fe" -- "cha" "tan" "fe" -- "liz,"
	"es" -- "ta" -- "re" -- "mos" "con" "el" "rey."
	"Na" -- "vi"
} % Lyrics

\lyricsto "voice 1" \new Lyrics \lyricmode {
	\set stanza = "2. "
	"Na" -- "vi" -- "dad," "Na" -- "vi" -- "dad," "na" -- "ci" -- "mien" -- "to" "de" "Je" -- "sús,"
	"Na" -- "vi" -- "dad," "Na" -- "vi" -- "dad," "blan" -- "ca es" -- "te" -- "la" "de" "quie" -- "tud,"
	"Na" -- "vi" -- "dad," "Na" -- "vi" -- "dad," "un" "e" -- "ter" -- "no" "res" -- "plan" -- "dor,"
	"de" "fe" -- "li" -- "ci" -- "dad" "y a" -- "mor."
} % Lyrics

\lyricsto "voice 1" \new Lyrics \lyricmode {
	\set stanza = "3. "
	"Na" -- "vi" -- "dad," "Na" -- "vi" -- "dad," "u" -- "na" "voz" "de e" -- "ter" -- "ni" -- "dad,"
	"Na" -- "vi" -- "dad," "Na" -- "vi" -- "dad," "u" -- "na" "voz" "de" "sal" -- "va" -- "ción,"
	"Na" -- "vi" -- "dad," "Na" -- "vi" -- "dad," "la es" -- "pe" -- "ran" -- "za en" -- "la o" -- "ra" -- "ción,"
	"y el" "mi" -- "la" -- "gro" "del" "a" -- "mor."
} % Lyrics
